trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
      docker pull zricethezav/gitleaks:latest
      docker run -v $(Build.SourcesDirectory):/path zricethezav/gitleaks:latest detect --source="/path" --config="/path/gitleaks.toml" --verbose --no-git
  displayName: 'Gitleaks'
