name: deepo CI
on: [push]
jobs:

    mxnet-py38-cu113_mxnet-py38_mxnet-cu113_mxnet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:mxnet-py38-cu113 -t ${{secrets.DOCKER_REPO}}:mxnet-py38 -t ${{secrets.DOCKER_REPO}}:mxnet-cu113 -t ${{secrets.DOCKER_REPO}}:mxnet -f docker/Dockerfile.mxnet-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:mxnet-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:mxnet-py38
                docker push ${{secrets.DOCKER_REPO}}:mxnet-cu113
                docker push ${{secrets.DOCKER_REPO}}:mxnet


    darknet-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:darknet-cpu -f docker/Dockerfile.darknet-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:darknet-cpu


    pytorch-py38-cpu_pytorch-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:pytorch-py38-cpu -t ${{secrets.DOCKER_REPO}}:pytorch-cpu -f docker/Dockerfile.pytorch-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:pytorch-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:pytorch-cpu


    paddle-py38-cpu_paddle-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:paddle-py38-cpu -t ${{secrets.DOCKER_REPO}}:paddle-cpu -f docker/Dockerfile.paddle-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:paddle-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:paddle-cpu


    paddle-py38-cu113_paddle-py38_paddle-cu113_paddle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:paddle-py38-cu113 -t ${{secrets.DOCKER_REPO}}:paddle-py38 -t ${{secrets.DOCKER_REPO}}:paddle-cu113 -t ${{secrets.DOCKER_REPO}}:paddle -f docker/Dockerfile.paddle-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:paddle-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:paddle-py38
                docker push ${{secrets.DOCKER_REPO}}:paddle-cu113
                docker push ${{secrets.DOCKER_REPO}}:paddle


    darknet-cu113_darknet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:darknet-cu113 -t ${{secrets.DOCKER_REPO}}:darknet -f docker/Dockerfile.darknet-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:darknet-cu113
                docker push ${{secrets.DOCKER_REPO}}:darknet


    chainer-py38-cpu_chainer-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:chainer-py38-cpu -t ${{secrets.DOCKER_REPO}}:chainer-cpu -f docker/Dockerfile.chainer-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:chainer-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:chainer-cpu


    keras-py38-cpu_keras-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:keras-py38-cpu -t ${{secrets.DOCKER_REPO}}:keras-cpu -f docker/Dockerfile.keras-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:keras-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:keras-cpu


    chainer-py38-cu113_chainer-py38_chainer-cu113_chainer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:chainer-py38-cu113 -t ${{secrets.DOCKER_REPO}}:chainer-py38 -t ${{secrets.DOCKER_REPO}}:chainer-cu113 -t ${{secrets.DOCKER_REPO}}:chainer -f docker/Dockerfile.chainer-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:chainer-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:chainer-py38
                docker push ${{secrets.DOCKER_REPO}}:chainer-cu113
                docker push ${{secrets.DOCKER_REPO}}:chainer


    keras-py38-cu113_keras-py38_keras-cu113_keras:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:keras-py38-cu113 -t ${{secrets.DOCKER_REPO}}:keras-py38 -t ${{secrets.DOCKER_REPO}}:keras-cu113 -t ${{secrets.DOCKER_REPO}}:keras -f docker/Dockerfile.keras-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:keras-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:keras-py38
                docker push ${{secrets.DOCKER_REPO}}:keras-cu113
                docker push ${{secrets.DOCKER_REPO}}:keras


    all-py38-cpu_all-cpu_py38-cpu_cpu_all-jupyter-py38-cpu_all-jupyter-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:all-py38-cpu -t ${{secrets.DOCKER_REPO}}:all-cpu -t ${{secrets.DOCKER_REPO}}:py38-cpu -t ${{secrets.DOCKER_REPO}}:cpu -t ${{secrets.DOCKER_REPO}}:all-jupyter-py38-cpu -t ${{secrets.DOCKER_REPO}}:all-jupyter-cpu -f docker/Dockerfile.all-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:all-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:all-cpu
                docker push ${{secrets.DOCKER_REPO}}:py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:cpu
                docker push ${{secrets.DOCKER_REPO}}:all-jupyter-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:all-jupyter-cpu

            - run: docker run ${{secrets.DOCKER_REPO}}:all-py38-cpu  python -c "import tensorflow as m; print(m.__name__, ':', m.__version__);import mxnet as m; print(m.__name__, ':', m.__version__);from tensorflow import keras as m; print(m.__name__, ':', m.__version__);import torch as m; print(m.__name__, ':', m.__version__);import chainer as m; print(m.__name__, ':', m.__version__);import paddle as m; print(m.__name__, ':', m.__version__);"
            - run: docker run ${{secrets.DOCKER_REPO}}:all-py38-cpu  darknet


    all-py38-cu113_all-py38_all-cu113_py38-cu113_all_cu113_py38_latest_all-jupyter-py38-cu113_all-jupyt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:all-py38-cu113 -t ${{secrets.DOCKER_REPO}}:all-py38 -t ${{secrets.DOCKER_REPO}}:all-cu113 -t ${{secrets.DOCKER_REPO}}:py38-cu113 -t ${{secrets.DOCKER_REPO}}:all -t ${{secrets.DOCKER_REPO}}:cu113 -t ${{secrets.DOCKER_REPO}}:py38 -t ${{secrets.DOCKER_REPO}}:latest -t ${{secrets.DOCKER_REPO}}:all-jupyter-py38-cu113 -t ${{secrets.DOCKER_REPO}}:all-jupyter-py38 -t ${{secrets.DOCKER_REPO}}:all-jupyter-cu113 -t ${{secrets.DOCKER_REPO}}:all-jupyter -f docker/Dockerfile.all-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:all-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:all-py38
                docker push ${{secrets.DOCKER_REPO}}:all-cu113
                docker push ${{secrets.DOCKER_REPO}}:py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:all
                docker push ${{secrets.DOCKER_REPO}}:cu113
                docker push ${{secrets.DOCKER_REPO}}:py38
                docker push ${{secrets.DOCKER_REPO}}:latest
                docker push ${{secrets.DOCKER_REPO}}:all-jupyter-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:all-jupyter-py38
                docker push ${{secrets.DOCKER_REPO}}:all-jupyter-cu113
                docker push ${{secrets.DOCKER_REPO}}:all-jupyter


    mxnet-py38-cpu_mxnet-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:mxnet-py38-cpu -t ${{secrets.DOCKER_REPO}}:mxnet-cpu -f docker/Dockerfile.mxnet-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:mxnet-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:mxnet-cpu


    pytorch-py38-cu113_pytorch-py38_pytorch-cu113_pytorch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:pytorch-py38-cu113 -t ${{secrets.DOCKER_REPO}}:pytorch-py38 -t ${{secrets.DOCKER_REPO}}:pytorch-cu113 -t ${{secrets.DOCKER_REPO}}:pytorch -f docker/Dockerfile.pytorch-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:pytorch-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:pytorch-py38
                docker push ${{secrets.DOCKER_REPO}}:pytorch-cu113
                docker push ${{secrets.DOCKER_REPO}}:pytorch


    tensorflow-py38-cpu_tensorflow-cpu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:tensorflow-py38-cpu -t ${{secrets.DOCKER_REPO}}:tensorflow-cpu -f docker/Dockerfile.tensorflow-py38-cpu .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:tensorflow-py38-cpu
                docker push ${{secrets.DOCKER_REPO}}:tensorflow-cpu


    tensorflow-py38-cu113_tensorflow-py38_tensorflow-cu113_tensorflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_REPO}}:tensorflow-py38-cu113 -t ${{secrets.DOCKER_REPO}}:tensorflow-py38 -t ${{secrets.DOCKER_REPO}}:tensorflow-cu113 -t ${{secrets.DOCKER_REPO}}:tensorflow -f docker/Dockerfile.tensorflow-py38-cu113 .
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_REPO}}:tensorflow-py38-cu113
                docker push ${{secrets.DOCKER_REPO}}:tensorflow-py38
                docker push ${{secrets.DOCKER_REPO}}:tensorflow-cu113
                docker push ${{secrets.DOCKER_REPO}}:tensorflow

